apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-component-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-component-sample
    app.kubernetes.io/part-of: go-application-sample
  name: go-component-sample
spec:
  selector:
    app.kubernetes.io/instance: go-component-sample
status:
  loadBalancer: {}
